
server:
  port: 81
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/sms?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db.migration,
  application:
    name: coupon
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8849
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml